apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "image-service.fullname" . }}-config-map
data:
  postgresql-server: {{ .Values.env.dbServer }}
  postgresql-database-name: {{ .Values.env.dbName }}
  postgresql-user-username: {{ .Values.env.dbUsername }}
  minio-access-key: {{ .Values.env.minioAccessKey }}
  minio-host: {{ .Values.env.minioHost }}