apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minio.name }}-pvc
spec:
  accessModes:
    - {{ .Values.minio.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.minio.pvc.storage }}