common:
  namespaceOverride: &namespaceOverride ""

  applicationName: &applicationName image-service
  dbApplicationName: &dbApplicationName image-service-db
  minioApplicationName: &minioApplicationName image-service-minio

  labels: &labels
    group: com.eupneart
    team: eupneart
    component: image-service
    phase: dev

app:
  applicationName: *applicationName
  namespaceOverride: *namespaceOverride
  labels: *labels
  deployment:
    image:
      repository: "eupneart/image-service"
      tag: "latest"
      pullPolicy: "Always"
    replicas: 1
    envFrom:
      app-cm:
        type: configmap
        nameSuffix: app-cm
      app-secret:
        type: secret
        nameSuffix: app-secret
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    containerSecurityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false   # should be set to true for production
    readinessProbe:
      enabled: true
      httpGet:
        path: /actuator/health/readiness
        port: 8080
    resources:
      limits:
        memory: 1Gi

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        name: http

  configMap:
    enabled: true
    files:
      app-cm:
        DB_SERVER: image-service-db    # The name of db service
        DB_NAME: image_service_db     # The name of the database used by the demo app
        DB_USERNAME: image_service     # A new created user for the demo app
        MINIO_BUCKET_NAME: images
        MINIO_INTERNAL_URL: http://image-service-minio:9000
        MINIO_EXTERNAL_URL: http://files.eupneart.com
        MINIO_USERNAME: admin
        NATS_URL: nats://nats:4222

  secret:
    enabled: true
    files:
      app-secret:
        data:
          DB_PASSWORD: MTIzNDU2Nzg=
          MINIO_PASSWORD: MTIzNDU2Nzg=       # userpassword  (12345678 in base64)

db:
  applicationName: *dbApplicationName
  namespaceOverride: *namespaceOverride
  labels: *labels
  deployment:
    image:
      repository: "postgres"
      tag: "16.3"
    replicas: 1
    envFrom:
      db-cm:
        type: configmap
        nameSuffix: postgres-cm
      db-secret:
        type: secret
        nameSuffix: postgres-secret
    initContainers:
      - name: db-init    # using root, change permissions to not use root in main container
        image: postgres:16.3
        command: 
          - 'sh'
          - '-c'
          - |
            chown -R 999:999 /var/lib/postgresql/data
        volumeMounts:
          - name:  image-service-db-data
            mountPath: /var/lib/postgresql/data
    containerSecurityContext:
      readOnlyRootFilesystem: false
      runAsUser: 999  # Default non-root user for the official Postgres image
      runAsGroup: 999

  persistence:
    enabled: true
    storageSize: 1Gi
    mountPVC: true
    mountPath: "/var/lib/postgresql/data"

  service:
    enabled: true
    ports:
    - port: 5432
      targetPort: 5432

  configMap:
    enabled: true
    files:
      postgres-cm:
        POSTGRES_DB: image_service_db     # The name of the database used by the demo app
        POSTGRES_USER: image_service     # A new created user for the demo app

  secret:
    enabled: true
    files:
      postgres-secret:
        data:
          POSTGRES_PASSWORD: MTIzNDU2Nzg=

minio:
  applicationName: *minioApplicationName
  namespaceOverride: *namespaceOverride
  labels: *labels
  deployment:
    image:
      repository: "minio/minio"
      tag: "latest"
    replicas: 1
    command:
      - /bin/bash
      - -c
    args:
      - minio server /storage --console-address :9001
    envFrom:
      db-cm:
        type: configmap
        nameSuffix: minio-cm
      db-secret:
        type: secret
        nameSuffix: minio-secret
    containerSecurityContext:
      runAsUser: 999

  persistence:
    enabled: true
    storageSize: 5Gi
    mountPVC: true
    mountPath: "/storage" 

  service:
    enabled: true
    type: NodePort
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: api
      - port: 9001
        targetPort: 9001
        protocol: TCP
        name: webui

  configMap:
    enabled: true
    files:
      minio-cm:
        MINIO_ROOT_USER: admin     # The name of the database used by the demo app
        MINIO_DEFAULT_BUCKETS: images     # A new created user for the demo app

  secret:
    enabled: true
    files:
      minio-secret:
        data:
          MINIO_ROOT_PASSWORD: MTIzNDU2Nzg=

