---
apiVersion: v1
kind: Namespace
metadata:
  name: eupneart-dev
  labels:
    environment: dev
    team: eupneart
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: eupneart-prd
  labels:
    environment: prd
    team: eupneart
    managed-by: argocd
