apiVersion: v1
kind: Secret
metadata:
    name: mysql-user-secret
type: Opaque
data:
    mysql-root-password: MTIzNDU2Nzg=       ## rootpassword (12345678 in base64)
    mysql-user-password: MTIzNDU2Nzg=       ## userpassword  (12345678 in base64)