apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config-map
data:
  mysql-server: {{ .Values.env.dbServer }}
  mysql-database-name: {{ .Values.env.dbName }}
  mysql-user-username: {{ .Values.env.dbUsername }}