apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.env.dbRootPassword }}
  mysql-user-password: {{ .Values.env.dbPassword }}