# Role Bindings for dev environment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-binding
  namespace: eupneart-dev
  labels:
    environment: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-role
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: eupneart-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-binding
  namespace: eupneart-dev
  labels:
    environment: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: eupneart-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-service-binding
  namespace: eupneart-dev
  labels:
    environment: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: ServiceAccount
    name: image-service
    namespace: eupneart-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: profile-service-binding
  namespace: eupneart-dev
  labels:
    environment: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: ServiceAccount
    name: profile-service
    namespace: eupneart-dev
---
# Role Bindings for prd environment
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-binding
  namespace: eupneart-prd
  labels:
    environment: prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-role
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: eupneart-prd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-binding
  namespace: eupneart-prd
  labels:
    environment: prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: eupneart-prd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-service-binding
  namespace: eupneart-prd
  labels:
    environment: prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: ServiceAccount
    name: image-service
    namespace: eupneart-prd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: profile-service-binding
  namespace: eupneart-prd
  labels:
    environment: prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: ServiceAccount
    name: profile-service
    namespace: eupneart-prd
