# Service Accounts for all services in dev environment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: eupneart-dev
  labels:
    app: api-gateway
    environment: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: eupneart-dev
  labels:
    app: frontend
    environment: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-service
  namespace: eupneart-dev
  labels:
    app: image-service
    environment: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-service
  namespace: eupneart-dev
  labels:
    app: profile-service
    environment: dev
---
# Service Accounts for all services in prd environment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: eupneart-prd
  labels:
    app: api-gateway
    environment: prd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: eupneart-prd
  labels:
    app: frontend
    environment: prd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-service
  namespace: eupneart-prd
  labels:
    app: image-service
    environment: prd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-service
  namespace: eupneart-prd
  labels:
    app: profile-service
    environment: prd
